-- COMENTÁRIOS
-- COMANDO PARA CRIAR BANCO DE DADOS
CREATE DATABASE hotel;

-- APAGAR BANCO DE DADOS
DROP DATABASE HOTEL;

-- APAGAR TABELA DE BANCO DE DAODS
DROP table CLIENTES;

-- ATIVAR BANCO DE DADOS
USE HOTEL;

-- CRIAR TABELAS
CREATE TABLE CLIENTES (
ID_CLIENTE INT auto_increment PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
ENDERECO VARCHAR(60) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL
);
