CREATE TABLE OFICINA_MOREIRA;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    TELEFONE CHAR(15) NOT NULL,
    EMAIL VARCHAR(10) NOT NULL,
    NOME_CLIENTE VARCHAR(50) NOT NULL,
    CPF_CLIENTE CHAR(11) NOT NULL UNIQUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS VEICULO (
    ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO_PROBLEMA TEXT (300) NOT NULL,
    PLACA CHAR(8) NOT NULL UNIQUE,
    COR VARCHAR(25) NOT NULL,
    QUILOMETRAGEM INT

);

CREATE TABLE IF NOT EXISTS MARCAS (
    ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_MARCA VARCHAR(50) NOT NULL,
    PAIS_ORIGEM VARCHAR(30),
    ANO_LANCAMENTO YEAR,
    MODELO TEXT(500),
    TIPO_COMBUSTIVEL ENUM('GASOLINA', 'DIESEL', "ETANOL") DEFAULT 'ETANOL'
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MODELO (
    ID_MODELO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_MODELO VARCHAR(50) NOT NULL,
    TIPO_MODELO ENUM('SEDAN', 'SUV', 'COMPACTO')DEFAULT 'COMPACTO',
    ANO_FABRICACAO YEAR NOT NULL,
    POTENCIA CHAR(10),
    STATUS_MODELO ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    DATA_CADSTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
    ID_FUNCIONARIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(50) NOT NULL,
    CPF_FUNCIONARIO CHAR(15) NOT NULL UNIQUE,
    TELEFONE_FUNCIONARIO CHAR(15) NOT NULL,
    CARGO_FUNCIONNARIO VARCHAR(30),
    SALARIO_FUNCIONARIO DECIMAL(10,2) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SERVICO (
    ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_SERVICO VARCHAR(100) NOT NULL,
    VALOR_SERVICO DECIMAL(10,2) NOT NULL,
    DATA_INICIO DATETIME NOT NULL,
    DATA_TERMINO DATETIME NOT NULL,
    DESCRICAO_SERVICO TEXT(500),
    STATUS_SERVICO ENUM('EM ANDAMENTO', 'EM ESPERA', 'CONCLUIDO') DEFAULT 'EM ANDAMENTO', NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

    CREATE TABLE IF NOT EXISTS FORNECEDOR (
        ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
        TELEFONE_FORNECEDOR CHAR(15) NOT NULL,
        CNPJ CHAR(18) NOT NULL UNIQUE,
        RAZAO_SOCIAL VARCHAR(100) NOT NULL,
        SEGMENTO_AREA VARCHAR(50) NOT NULL,
        ENDERECO VARCHAR(100) NOT NULL,
        EMAIL VARCHAR(100) NOT NULL,
        STATUS_FORNECEDOR ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
        DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );